"use strict";
exports.__esModule = true;
var Question_1 = require("./ex1/Question");
exports.Question = Question_1.Question;
var ShortAnswerQuestion_1 = require("./ex1/ShortAnswerQuestion");
exports.ShortAnswerQuestion = ShortAnswerQuestion_1.ShortAnswerQuestion;
var MultipleChoiceQuestion_1 = require("./ex1/MultipleChoiceQuestion");
exports.MultipleChoiceQuestion = MultipleChoiceQuestion_1.MultipleChoiceQuestion;
var QuestionsCatalog_1 = require("./ex2/QuestionsCatalog");
exports.QuestionsCatalog = QuestionsCatalog_1.QuestionsCatalog;
var Questionnaire_1 = require("./ex3/Questionnaire");
exports.Questionnaire = Questionnaire_1.Questionnaire;
